
CREATE PROCEDURE [dbo].[GetListSongs]
@SEARCH_TEXT AS VARCHAR(50)='',
@SORT_COLUMN_NAME AS VARCHAR(50)='',
@SORT_COLUMN_DIRECTION AS VARCHAR(50)='',
@START_INDEX AS INT=0,
@PAGE_SIZE AS INT=10
AS
BEGIN
	DECLARE @QUERY AS VARCHAR(MAX)='',@ORDER_QUERY AS VARCHAR(MAX)='',@CONDITIONS AS VARCHAR(MAX)='',
	@PAGINATION AS VARCHAR(MAX)=''

	SET @QUERY='SELECT * FROM song '

	-- SEARCH OPERATION
	IF(ISNULL(@SEARCH_TEXT,'')<>'')
	BEGIN
		
		SET @CONDITIONS='WHERE title LIKE ''%'+@SEARCH_TEXT+'%'' '
		
	END

	-- SORT OPERATION
	IF(ISNULL(@SORT_COLUMN_NAME,'')<>'' AND ISNULL(@SORT_COLUMN_DIRECTION,'')<>'')
	BEGIN
		SET @ORDER_QUERY=' ORDER BY '+@SORT_COLUMN_NAME+' '+@SORT_COLUMN_DIRECTION
	END
	ELSE SET @ORDER_QUERY=' ORDER BY songID ASC'

	-- PAGINATION OPERATION
	IF(@PAGE_SIZE>0)
	BEGIN
		SET @PAGINATION=' OFFSET '+(CAST(@START_INDEX AS varchar(10)))+' ROWS
		FETCH NEXT '+(CAST(@PAGE_SIZE AS varchar(10)))+' ROWS ONLY'
	END

	IF(@CONDITIONS<>'') SET @QUERY+=@CONDITIONS
	IF(@ORDER_QUERY<>'') SET @QUERY+=@ORDER_QUERY
	IF(@PAGINATION<>'') SET @QUERY+=@PAGINATION

	PRINT(@QUERY)
	EXEC(@QUERY)
END